services:
  caddy:
    image: ghcr.io/picosh/pico/caddy:latest
    restart: always
    networks:
      - git
    env_file:
      - .env.prod
    environment:
      APP_DOMAIN: pr.pico.sh
      APP_EMAIL: hello@pico.sh
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/git-caddy/data:/data
      - ./data/git-caddy/config:/config
    ports:
      - "${GITPR_HTTPS_V4:-443}:443"
      - "${GITPR_HTTP_V4:-80}:80"
      - "${GITPR_HTTPS_V6:-[::1]:443}:443"
      - "${GITPR_HTTP_V6:-[::1]:80}:80"
  web:
    command: "/app/git-web --config ${GITPR_CONFIG_PATH}"
    networks:
      git:
        aliases:
          - web
    env_file:
      - .env.prod
  ssh:
    command: "/app/git-ssh --config ${GITPR_CONFIG_PATH}"
    networks:
      git:
        aliases:
          - ssh
    env_file:
      - .env.prod
    ports:
      - "${GITPR_SSH_V4:-22}:2222"
      - "${GITPR_SSH_V6:-[::1]:22}:2222"
networks:
  git:
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: pr
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - subnet: fd00:dead:beef:28::/112
