services:
  web:
    image: ghcr.io/picosh/pico/git-web:latest
    restart: always
    volumes:
      - ./data/git-pr/data:/app/data
  ssh:
    image: ghcr.io/picosh/pico/git-ssh:latest
    restart: always
    volumes:
      - ./data/git-pr/data:/app/data
