# url is used for help commands, exclude protocol
url = "localhost"
# where we store the sqlite db, this toml file, and ssh host keys
data_dir = "./data"
# list of admin ssh pubkeys, authorized to submit review and other admin
# permissions
admins = []
# set datetime format for our clients
time_format = "2006-01-02"
# who can create new repos?
#   admin: only admins
#   user: admins and users
create_repo = "user"
# add a description box to the top of the index page, supports HTML
desc = ""
